name: test
on:
- pull_request
jobs:
  vapor-integration:
    runs-on: ubuntu-latest
    container: 
      image: swift:5.7
    steps:
      - name: Check out package
        uses: actions/checkout@v3
        with: { path: 'websocket-kit' }
      - name: Check out Vapor
        uses: actions/checkout@v3
        with: { repository: 'vapor/vapor', path: 'vapor' }
      - name: Use local package in Vapor
        run: |
          swift package --package-path vapor edit websocket-kit --path websocket-kit
      - name: Run Vapor tests
        run: swift test --package-path vapor

  unit-tests:
    uses: vapor/ci/.github/workflows/run-unit-tests.yml@reusable-workflows
    with:
      with_coverage: true
      with_tsan: false
      coverage_ignores: '/Tests/'
      with_public_api_check: ${{ github.event_name == 'pull_request' }}

